#!/bin/csh

if (  $#argv != 4) then
  echo '   '
  echo ' Syntax: o_Setorder.sh  <file.dat>  <indexi>  <type_of_table>  <output tex file>'
  echo '  '
  echo '  file.dat:  datas generated by ADGFEM in file order.dat '
  echo ' indexi:  1 (h_max), 2 (h_aver), 3 (tau),  4 (DOF), 5(ST DOF), 6(p)'
  echo ' type of table: RES, RES-ST-book, AMA, AMApap, .... (see .f90)'
  echo '   '
else

## OLD VARIANT

#cp $argv[1] order.dat
# ~/adgfem/Scripts/Setorderx  $argv[2] $argv[3]

## NEW VARIANT
rm -f  tab_beg.tex tab.tex tab_end.tex
 ~/adgfem/SRC_O/Setorderx $argv[1]  $argv[2] $argv[3]
cat tab_beg.tex tab.tex tab_end.tex > $argv[4]

#cp $argv[4] tabtab.tex
#pdflatex ~/adgfem/Scripts/test-tab > smaz
endif
